server:
  port: 8088
spring:
  config:
    import: "nacos:"
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848/test-dev.yml
        namespace: test
        group: DEFAULT_GROUP
        import-check:
          enabled: false
